### ISSUE TITLE
Inference or visualization for nnUNet_ext

### ISSUE THREAD

**Issue by vivian-2727** [MECLabTUDA/Lifelong-nnUNet#4]
I noticed that you put some visualization pictures in github. Whether does nnunet_ext provide inference script to save prediction results of the incremental learning model (like EWC, LWF, ...)?

**Comment by amrane99** [comment]
Hey,

- we have an Evaluator that can be used to perform validation, see the documentation [here](https://github.com/MECLabTUDA/Lifelong-nnUNet/blob/main/documentation/evaluation.md). This however only calculates Dice and IoU, so it does not store the generated predictions.
- Intermediate (subject-specific) results are automatically stored during training. For this, the argument `-save_interval` can be modified, see [here](https://github.com/MECLabTUDA/Lifelong-nnUNet/blob/main/documentation/multihead_training.md) for correct use.
- Additionally, _to generate and store predictions_, please have a look at the dev-inference branch, where we have a script that [extracts predictions](https://github.com/MECLabTUDA/Lifelong-nnUNet/blob/dev-inference/extract_predictions.py). Since it's still in development we haven't merged it with the main branch yet, but it can surely be used :)

To answer the question; inference scripts are provided in the [dev-inference branch](https://github.com/MECLabTUDA/Lifelong-nnUNet/tree/dev-inference).
Best

**Comment by adwaykanhere** [comment]
Hi @amrane99, will the "extract predictions" script be able to generate predictions on the test set? For example, say I have datasets #700 and #701 that I'm training a sequential trainer on and then testing on the 'imagesTs' folder from dataset #702.

Also in your script, It's not clear what the 'current_checkpoint_root' folder is. If I'm following the readme from the main branch, I only have the paths that I have set up for Lifelong-nnUNet. Could you please explain this too? 

Thanks,
Adway

**Comment by amrane99** [comment]
Hi @adwaykanhere,
firstly, the inference script is from the [dev-inference branch](https://github.com/MECLabTUDA/Lifelong-nnUNet/tree/dev-inference). As commented in the code, there is a part of the code that is used to modify the paths in the model checkpoints in case the nnU-Net paths have been changed before performing the actual inference. Regarding your question, the `current_checkpoint_root` folder is the substring of the old and new paths that are equal (see [line 28](https://github.com/MECLabTUDA/Lifelong-nnUNet/blob/dev-inference/extract_predictions.py#L28)).

So to do inference, have a look at the [extract predictions script](https://github.com/MECLabTUDA/Lifelong-nnUNet/blob/dev-inference/extract_predictions.py), here are some details:
- Lines [27 - 39](https://github.com/MECLabTUDA/Lifelong-nnUNet/blob/dev-inference/extract_predictions.py#L27): Change checkpoint paths if the data checkpoints have been moved
- Lines [41 - 48](https://github.com/MECLabTUDA/Lifelong-nnUNet/blob/dev-inference/extract_predictions.py#L41): Pre-process data folder for inference if not already done
- Lines [50 - 61](https://github.com/MECLabTUDA/Lifelong-nnUNet/blob/dev-inference/extract_predictions.py#L50): Actual part that runs the inference

Best,
Amin

**Comment by adwaykanhere** [comment]
Hi @amrane99, thank you very much! When I try to run the script I get the following error 
```
ModuleNotFoundError: No module named 'nnunet_ext.run.run_inference
```
I have installed everything correctly and I was able to train using the extension too but I don't know why I'm receiving this message.

**Comment by amrane99** [comment]
Hi @adwaykanhere,

try to navigate into the downloaded source code where setup.py lives and execute `pip install -e .`. This should install the source code and you can use the modules accordingly.

Best,
Amin

**Comment by adwaykanhere** [comment]
Thanks @amrane99. I tried to install it using the command and while I get the following success message for install, when I run the inference script again I still get the same error. 

<img width="795" alt="Screenshot 2023-11-06 at 12 42 45 PM" src="https://github.com/MECLabTUDA/Lifelong-nnUNet/assets/22454450/b5255778-b933-4c12-8943-d7b6b015fa99">

**Comment by adwaykanhere** [comment]
Thanks @amrane99 that worked! However, now when I run the script I get the error
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/akanhere/nnunet/RESULTS/nnUNet_ext/3d_fullres/Task711_Ped_Fresh_Task713_Peds_Fine/Task713_Peds/nnUNetTrainerLWF__nnUNetPlansv2.1/Generic_UNet/SEQ/plans.pkl'

```
I don't have an nnUNet_ext folder itself in the RESULTS folder but I'm seeing a similar structure in the EVAL folder but the last folder there seems to be empty too.

**Comment by amrane99** [comment]
Then you have set the wrong paths in your script. Verify that the paths are correct as you want them to be.
At this point I can’t help without further context on the paths you set and the model you intend to use etc.

**Comment by adwaykanhere** [comment]
Hi @amrane99, I have double checked the paths and ensured that they are setup as described in the [README](https://github.com/MECLabTUDA/Lifelong-nnUNet/blob/main/documentation/setting_up_paths.md) The command that I'm running for LwF trainer is as follows 
```
nnUNet_train_lwf 3d_fullres -t 711 713 -f 0 -lwf_temperature 0.75 -num_epoch 250 -d 3 -save_interval 25 -s seg_outputs --store_csv
```
What am I doing wrong? Thanks so much for your support!

**Comment by amrane99** [comment]
@adwaykanhere
Your problem is unrelated to the actual issue topic as you want to train and not extract predictions.
If this problem still exists open a corresponding issue.
